### PR TITLE
Translation of ENUM

### PR DESCRIPTION
**Pull request by colasbd**

### CODE REVIEW

**Comment by AliSoftware** [comment]
Hi @colasbd 

I don't understand how you did that Pull Request. As you can see in the "Files changed" tab on GitHub, the diff of this PR contains changes that are _already_ present in the `feature/english-readme` branch. It makes no sense to see them _again_ and to merge those changes _again_, that diff should only contain the new paragraph(s) you translated, not the whole translation again and again.

You probably forgot to update your fork to make it synchronised with the new commits we've pushed on this repo since you forked, so your fork is late by some commits on ours. Please re-sync your fork and rebase those changes so that this PR is clean again.

**Comment by colasbd** [comment]
I would say it looks like a bug (?) of the diff feature.
I used the "edit in the web interface" of github.

**Comment by AliSoftware** [comment]
Not really a bug. It's how git works, it's quite logical.

Your fork is at one point in the commit history, our repo is later in the history with more commits since you forked.
So if you use the "edit in the web interface" feature of GitHub on your fork, it will edit the file on your fork, which means that it will edit at the point where your fork is, which is a a few commits behind our official repo.
You need to update your fork first (or removing your fork and creating another one, but that would seem quite overkill) before re-using the "edit in the web interface" on your fork, so that editing in GitHub edits the last commit, not some old commit if you forgot to synchronise your fork with ours.

**Comment by colasbd** [comment]
👍 
Note that I used the "edit in the web interface" on your branch. But since I already created a fork I think Git used this fork.

I have created a new fork.

**Pull request closed without merging**
